### PR TITLE
Support Jekyll 2 & 3

### PR DESCRIPTION
**Pull request by neverpanic**
This is a cherry pick from commit octopress/quote-tag@d01af22.

See jekyll/jekyll#3662.

### CODE REVIEW

**Comment by neverpanic** [comment]
This supersedes #6, which would require branching or dropping support for Jekyll 2.

**Comment by neontapir** [comment]
Is there any chance this will get merged soon? I'm running into the issue this PR addressses.

**Comment by neverpanic** [comment]
@neontapir  I am not working on this anymore, but feel free to pick it up if it needs fixing.

**Comment by lmno** [comment]
+1 for merging this PR

**Comment by neverpanic** [comment]
I'm closing this because I no longer intend to work on it.

**Pull request closed without merging**
